version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- choco install opencover.portable
- choco install codecov
after_test:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --framework net462 --verbosity q"
- codecov -f "results.xml" 
artifacts:
- path: '**\*.nupkg'
