version: 1.0.{build}
image: Visual Studio 2019
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - master
configuration: Release
build_script:
    - cmd: dotnet build -c Release /m
test_script:
    - cmd: dotnet test -c Release --no-build
after_test:
    - choco install codecov
    - codecov --help
    - codecov -f "TestResults\*.opencover.xml"
artifacts:
    - path: '**\*.nupkg'
      name: nupkg
    - path: '**\*.snupkg'
      name: snupkg
nuget:
    disable_publish_on_pr: true
deploy:
    provider: NuGet
    api_key:
        secure: rE/5DvmyqGe9RdSRHDF7HF0MZoQzhb84P9cipIK8uY4TPf1Fix+67biwICQ4qHDB
    skip_symbols: false
    symbol_server:
    on:
        branch: master
        #appveyor_repo_tag: true
