version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - master
configuration: Release
build_script:
    - cmd: dotnet build -c Release /m
test_script:
    - cmd: dotnet test -c Release --no-build
after_test:
    - choco install codecov
    - codecov -h
    - codecov -f 'TestResults/NetUtils.Tests.opencover.xml'
artifacts:
    - path: '**\*.nupkg'
      name: nupkg
    - path: '**\*.snupkg'
      name: snupkg
nuget:
    disable_publish_on_pr: true
deploy:
    provider: NuGet
    api_key:
        secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
